// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnycjmnqlkqxvnsqwymz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ueWNqbW5xbGtxeHZuc3F3eW16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTUxMzEsImV4cCI6MjA2MjgzMTEzMX0.oq5stPPvHGoO2ZcfFVX7YNr572Oh7KJVq1ZsMJR2l8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);